name: .NET Core

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Set Version
      run: |
        tmp_version="$(git describe --tags --long | sed 's/v\(.*\)-\(.*\)-.*/\1.\2/')"
        echo "Version: $tmp_version"
        echo tmp_version="$tmp_version" >> $env:GITHUB_ENV
        . ./ver.sh
        set-ver "$tmp_version"
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: ./publish.sh
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: cx-auto-sign-publish
        path: out/cx-auto-sign.tar.gz
