name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    if: ${{ github.repository == 'moeshin/cx-auto-sign' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: ./publish.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/cx-auto-sign.tar.gz
